import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { FiArrowUpRight, FiChevronDown, FiGithub, FiLayers, FiLinkedin, FiMail, FiMonitor, FiPhone } from 'react-icons/fi';
import CursorGlow from '../components/CursorGlow';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import ScrollProgress from '../components/ScrollProgress';
import Button from '../components/common/Button';
import Container from '../components/common/Container';
import Reveal from '../components/common/Reveal';

const projects = [
  { name: 'Wanderlust', category: 'Open-source web project', description: 'A travel-inspired portfolio project published as an open-source codebase, with the implementation available to explore on GitHub.', impact: 'Shows an end-to-end approach to building and sharing a web application.', stack: ['Open source', 'Web application'], github: 'https://github.com/poonam-gh/Wanderlust', visual: 'from-orange-400/25 via-rose-500/10 to-transparent', mark: 'WL' },
  { name: 'Songify', category: 'Open-source web project', description: 'A music-inspired portfolio project published as an open-source codebase, with the full implementation available on GitHub.', impact: 'Demonstrates an interest in thoughtful, product-oriented web experiences.', stack: ['Open source', 'Web application'], github: 'https://github.com/poonam-gh/Songify', visual: 'from-lime-400/20 via-green-500/10 to-transparent', mark: 'SG' },
  { name: 'Timetable Generator', category: 'Optimisation \u00b7 Streamlit', description: 'An automated scheduling tool that uses optimisation logic to replace repetitive timetable planning with a guided interface.', impact: 'Reduces manual scheduling effort through automated generation.', stack: ['Python', 'Streamlit', 'Optimisation'], visual: 'from-emerald-500/25 via-cyan-500/10 to-transparent', mark: 'TG' },
  { name: 'AI Movie Recommender', category: 'Machine learning \u00b7 Streamlit', description: 'An AI-powered movie recommendation experience with a focused, interactive interface for personalised suggestions.', impact: 'Brings recommendation algorithms into a simple, usable product flow.', stack: ['Python', 'Streamlit', 'Machine Learning'], visual: 'from-violet-500/30 via-blue-500/10 to-transparent', mark: 'AI' },
];

const skillGroups = [
  ['Languages', ['C++', 'Python', 'JavaScript', 'C#']],
  ['Frontend', ['React', 'HTML', 'CSS', 'Tailwind CSS']],
  ['Backend', ['Node.js', 'Express.js', 'ASP.NET MVC', 'REST APIs']],
  ['Databases', ['MongoDB', 'MySQL', 'SQL Server', 'PostgreSQL']],
  ['Tools', ['Git', 'GitHub', 'Azure DevOps', 'Postman']],
  ['AI engineering', ['LangChain', 'LlamaIndex', 'RAG', 'AI Agents', 'FastAPI', 'Vector Databases']],
];

const experience = [
  { role: 'Software Engineer', duration: '2025 - 2026', label: 'Enterprise applications', summary: ['Developed, enhanced, and maintained 5+ enterprise web applications used across multiple business teams.', 'Delivered 10+ feature enhancements by translating user requests and business requirements into production changes.', 'Upgraded 5+ legacy applications to newer framework and jQuery versions, improving maintainability and compatibility.', 'Debugged production issues, tested releases, and supported deployments with post-deployment validation.'], technologies: ['ASP.NET MVC', 'C#', 'SQL Server', 'JavaScript', 'jQuery', 'HTML', 'CSS', 'Git', 'Azure DevOps'] },
  { role: 'Software Engineer Intern', duration: 'Internship', label: 'Application engineering', summary: ['Implemented feature enhancements and resolved application issues.', 'Worked with ASP.NET MVC, C#, SQL Server, JavaScript, HTML, CSS, and jQuery.', 'Participated in Agile processes and collaborated with senior developers.', 'Performed debugging, testing, and deployment support.'], technologies: ['ASP.NET MVC', 'C#', 'SQL Server', 'JavaScript', 'HTML', 'CSS', 'jQuery'] },
];

function SectionHeading({ label, title, children }) {
  return <Reveal className="max-w-3xl"><p className="section-label">{label}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.045em] text-white sm:text-4xl lg:text-[2.8rem]">{title}</h2>{children && <p className="mt-5 text-lg leading-8 text-zinc-400 sm:text-xl">{children}</p>}</Reveal>;
}

function ExperienceTimeline() {
  const [expandedRole, setExpandedRole] = useState('');
  return <div className="relative mt-14 ml-2 space-y-6 border-l border-white/10 pl-8 sm:ml-4 sm:pl-12">{experience.map((entry, index) => {
    const isExpanded = expandedRole === entry.role;
    return <Reveal key={entry.role} delay={index * 0.08} className="relative"><motion.div initial={{ scale: 0 }} whileInView={{ scale: 1 }} viewport={{ once: true }} transition={{ delay: 0.15 + index * 0.08 }} className="absolute -left-[37px] top-7 size-2.5 rounded-full bg-blue-400 shadow-[0_0_0_5px_rgba(59,130,246,0.12)] sm:-left-[53px]" /><article className="surface rounded-2xl p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="section-label">{entry.duration}</p><h3 className="mt-3 text-2xl font-semibold tracking-tight sm:text-[1.65rem]">{entry.role}</h3><p className="mt-1 text-base text-zinc-400">Emerson</p></div><span className="w-fit rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs text-zinc-400">{entry.label}</span></div><ul className="mt-8 space-y-3.5 text-base leading-7 text-zinc-400">{entry.summary.slice(0, 2).map((achievement) => <li key={achievement} className="flex gap-3"><span className="mt-2.5 size-1.5 shrink-0 rounded-full bg-blue-400/80" />{achievement}</li>)}</ul><AnimatePresence initial={false}>{isExpanded && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25 }} className="overflow-hidden"><ul className="mt-3.5 space-y-3.5 text-base leading-7 text-zinc-400">{entry.summary.slice(2).map((achievement) => <li key={achievement} className="flex gap-3"><span className="mt-2.5 size-1.5 shrink-0 rounded-full bg-blue-400/80" />{achievement}</li>)}</ul><p className="mt-8 text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Technologies used</p><div className="mt-3 flex flex-wrap gap-2">{entry.technologies.map((tech) => <span key={tech} className="rounded-md border border-white/[0.08] bg-white/[0.03] px-2.5 py-1 text-xs text-zinc-400">{tech}</span>)}</div></motion.div>}</AnimatePresence><button type="button" className="mt-8 inline-flex items-center gap-2 text-sm font-medium text-blue-300 transition-colors hover:text-blue-200" onClick={() => setExpandedRole(isExpanded ? '' : entry.role)} aria-expanded={isExpanded}>{isExpanded ? 'Show less' : 'View achievements and technologies'}<FiChevronDown className={`transition-transform ${isExpanded ? 'rotate-180' : ''}`} /></button></article></Reveal>;
  })}</div>;
}

function ProjectCard({ project, index }) {
  return <Reveal delay={index * 0.06}><motion.article whileHover={{ y: -6 }} transition={{ duration: 0.25 }} className="group surface h-full overflow-hidden rounded-2xl"><div className={`relative flex aspect-[16/8] items-center justify-center overflow-hidden bg-gradient-to-br ${project.visual}`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_120%,rgba(255,255,255,0.15),transparent_45%)]" /><motion.div whileHover={{ scale: 1.08, rotate: 2 }} className="relative flex size-20 items-center justify-center rounded-2xl border border-white/20 bg-[#0b0b0e]/70 text-lg font-semibold tracking-tight text-white shadow-xl backdrop-blur-md">{project.mark}</motion.div><span className="absolute bottom-4 left-5 text-sm font-medium text-zinc-300">{project.category}</span></div><div className="p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><h3 className="text-2xl font-semibold tracking-tight">{project.name}</h3><FiLayers className="mt-1 shrink-0 text-zinc-500" /></div><p className="mt-4 text-base leading-7 text-zinc-400">{project.description}</p><p className="mt-5 border-l border-blue-400/70 pl-3 text-base leading-7 text-zinc-300">{project.impact}</p><div className="mt-6 flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="rounded-md border border-white/[0.08] bg-white/[0.04] px-2.5 py-1 text-xs text-zinc-400">{item}</span>)}</div><div className="mt-7 flex gap-5 border-t border-white/[0.08] pt-5 text-sm">{project.github ? <a href={project.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-zinc-300 transition-colors hover:text-white"><FiGithub /> View on GitHub <FiArrowUpRight /></a> : <a href="#contact" className="inline-flex items-center gap-1.5 text-blue-300 transition-colors hover:text-blue-200">Project details <FiArrowUpRight /></a>}</div></div></motion.article></Reveal>;
}

function LoadingScreen({ visible }) {
  return <AnimatePresence>{visible && <motion.div initial={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.35 }} className="fixed inset-0 z-[70] flex items-center justify-center bg-[#09090B]"><motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="text-xl font-semibold tracking-tight">PC<span className="text-blue-400">.</span></motion.div></motion.div>}</AnimatePresence>;
}

function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 460); return () => window.clearTimeout(timer); }, []);
  return <><LoadingScreen visible={loading} /><CursorGlow /><ScrollProgress /><main className="relative z-10"><Navbar /><Hero />
    <section id="about" className="section-anchor border-t border-white/[0.08] py-24 sm:py-32"><Container><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><SectionHeading label="About" title="Engineering is a practice of making complexity useful." /><Reveal delay={0.12} className="space-y-7 text-lg leading-8 text-zinc-400 sm:text-xl"><p>I build and maintain software with a practical mindset - understanding business requirements, improving existing systems, and delivering reliable solutions that users can depend on. During my time at Emerson, I contributed to enterprise applications, implemented feature enhancements, resolved production issues, and collaborated in Agile teams to deliver quality software.</p><p>Alongside my professional experience, I&apos;m continuously expanding my skills in backend engineering, system design, cloud technologies, and AI Engineering. My goal is to build software that is scalable, maintainable, and solves meaningful real-world problems.</p><div className="grid gap-3 pt-2 sm:grid-cols-3">{[['Solve', 'Start with the real problem.'], ['Learn', 'Go deep on the system.'], ['Improve', 'Leave it more reliable.']].map(([title, text]) => <div key={title} className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><p className="text-base font-medium text-white">{title}</p><p className="mt-1 text-sm leading-6 text-zinc-500">{text}</p></div>)}</div></Reveal></div></Container></section>
    <section id="experience" className="section-anchor bg-white/[0.012] py-24 sm:py-32"><Container><SectionHeading label="Experience" title="Building dependable software in a production environment.">Enterprise experience that supports a growing foundation in backend systems, cloud technologies, and AI Engineering.</SectionHeading><ExperienceTimeline /></Container></section>
    <section id="projects" className="section-anchor border-y border-white/[0.08] py-24 sm:py-32"><Container><SectionHeading label="Selected projects" title="Learning in public, building with intent.">A collection of software engineering projects showcasing full-stack development, backend systems, APIs, and responsive web applications.</SectionHeading><div className="mt-14 grid gap-6 md:grid-cols-2">{projects.map((project, index) => <ProjectCard key={project.name} project={project} index={index} />)}</div></Container></section>
    <section id="skills" className="section-anchor py-24 sm:py-32"><Container><SectionHeading label="Capabilities" title="A software foundation, with AI depth in progress.">A working toolkit across enterprise development and the AI technologies I&apos;m actively studying and applying.</SectionHeading><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{skillGroups.map(([group, skills], index) => <Reveal key={group} delay={index * 0.045}><motion.div whileHover={{ y: -3 }} className="surface h-full rounded-xl p-6"><h3 className="text-lg font-medium text-zinc-100">{group}</h3><div className="mt-4 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="rounded-md bg-white/[0.05] px-2.5 py-1.5 text-sm text-zinc-400">{skill}</span>)}</div></motion.div></Reveal>)}</div></Container></section>
    <section id="contact" className="section-anchor border-t border-white/[0.08] py-24 sm:py-32"><Container><Reveal><div className="relative overflow-hidden rounded-2xl border border-white/[0.1] bg-zinc-900/55 px-6 py-14 text-center shadow-2xl shadow-black/20 sm:px-12 sm:py-20"><div className="pointer-events-none absolute -top-20 left-1/2 size-64 -translate-x-1/2 rounded-full bg-blue-500/[0.10] blur-3xl" /><div className="relative"><p className="section-label">Let&apos;s connect</p><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-semibold tracking-[-0.045em] sm:text-4xl">Interested in building reliable software and practical AI?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-zinc-400">I&apos;m Poonam Chapke, a Software Engineer in Bangalore building toward AI Software Engineering roles.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button href="mailto:pschapke11@gmail.com"><FiMail /> pschapke11@gmail.com</Button><Button href="tel:+918446943447" variant="secondary"><FiPhone /> +91 8446943447</Button></div><div className="mt-7 flex justify-center gap-5"><a href="https://github.com/poonam-gh" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-zinc-400 transition-colors hover:text-white"><FiGithub /> GitHub</a><a href="https://www.linkedin.com/in/poonam-chapke-519393229/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-zinc-400 transition-colors hover:text-white"><FiLinkedin /> LinkedIn</a><Button href="#top" variant="ghost" className="!p-0"><FiMonitor /> Back to top</Button></div></div></div></Reveal><footer className="flex flex-col gap-3 py-10 text-base text-zinc-600 sm:flex-row sm:items-center sm:justify-between"><span>&copy; 2026 Poonam Chapke &bull; Bangalore, Karnataka, India</span><span>Software Engineer &bull; Exploring AI Engineering</span></footer></Container></section>
  </main></>;
}

export default Home;
